###
 # @author Alex Carrega <contact@alexcarrega.com>
 # @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 ##

name: axc.datamanagement::lang.abbreviation.label.singular
form: @/plugins/axc/datamanagement/models/abbreviation/fields.yaml
modelClass: AxC\DataManagement\Models\Abbreviation
defaultRedirect: axc/datamanagement/abbreviation

create:
  title: backend::lang.form.create_title
  redirect: axc/datamanagement/abbreviation/update/:id
  redirectClose: axc/datamanagement/Abbreviation
  flashSave: backend::lang.form.create_success

update:
  title: backend::lang.form.update_title
  redirect: axc/datamanagement/abbreviation/update/:id
  redirectClose: axc/datamanagement/abbreviation
  flashSave: backend::lang.form.update_success
  flashDelete:  backend::lang.form.delete_success