###
 # @author Alex Carrega <contact@alexcarrega.com>
 # @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 ##

name: axc.datamanagement::lang.phone.label.singular
form: @/plugins/axc/datamanagement/models/phone/fields.yaml
modelClass: AxC\DataManagement\Models\Phone
defaultRedirect: axc/datamanagement/phone

create:
  title: backend::lang.form.create_title
  redirect: axc/datamanagement/phone/update/:id
  redirectClose: axc/datamanagement/Phone
  flashSave: backend::lang.form.create_success

update:
  title: backend::lang.form.update_title
  redirect: axc/datamanagement/phone/update/:id
  redirectClose: axc/datamanagement/phone
  flashSave: backend::lang.form.update_success
  flashDelete:  backend::lang.form.delete_success

preview:
  title: backend::lang.form.preview_title