###
 # @author Alex Carrega <contact@alexcarrega.com>
 # @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 ##

title: axc.datamanagement::lang.phone.label.singular
list: @/plugins/axc/datamanagement/models/phone/columns.yaml
modelClass: AxC\DataManagement\Models\Phone
recordUrl: axc/datamanagement/phone/update/:id
noRecordsMessage: backend::lang.list.no_records
filter: filter_config.yaml
recordsPerPage: 20
showCheckboxes: true
#recordOnClick: $.axc_framework_form_modal.updateRecord(:id)
showSetup: true
toolbar:
#  buttons: @/plugins/axc/framework/partials/backend/controllers/modal/toolbars/index.htm
  buttons: @/plugins/axc/framework/partials/backend/controllers/toolbars/index.htm
  search:
    prompt: backend::lang.list.search_prompt