###
 # @author Alex Carrega <contact@alexcarrega.com>
 # @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 ##

name: axc.datamanagement::lang.insurance.content.label.singular
form: @/plugins/axc/datamanagement/models/insurance-content/fields.yaml
modelClass: AxC\DataManagement\Models\InsuranceContent
defaultRedirect: axc/datamanagement/insurancecontent

create:
  title: backend::lang.form.create_title
  redirect: axc/datamanagement/insurancecontent/update/:id
  redirectClose: axc/datamanagement/insurancecontent
  flashSave: backend::lang.form.create_success

update:
  title: backend::lang.form.update_title
  redirect: axc/datamanagement/insurancecontent/update/:id
  redirectClose: axc/datamanagement/insurancecontent
  flashSave: backend::lang.form.update_success
  flashDelete:  backend::lang.form.delete_success