###
 # @author Alex Carrega <contact@alexcarrega.com>
 # @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 ##

name: axc.datamanagement::lang.route.label.singular
form: @/plugins/axc/datamanagement/models/route/fields.yaml
modelClass: AxC\DataManagement\Models\Route
defaultRedirect: axc/datamanagement/route

create:
  title: backend::lang.form.create_title
  redirect: axc/datamanagement/route/update/:id
  redirectClose: axc/datamanagement/Route
  flashSave: backend::lang.form.create_success

update:
  title: backend::lang.form.update_title
  redirect: axc/datamanagement/route/update/:id
  redirectClose: axc/datamanagement/route
  flashSave: backend::lang.form.update_success
  flashDelete:  backend::lang.form.delete_success

preview:
  title: backend::lang.form.preview_title