###
 # @author Alex Carrega <contact@alexcarrega.com>
 # @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 ##

name: axc.datamanagement::lang.link.label.singular
form: @/plugins/axc/datamanagement/models/link/fields.yaml
modelClass: AxC\DataManagement\Models\Link
defaultRedirect: axc/datamanagement/link

create:
  title: backend::lang.form.create_title
  redirect: axc/datamanagement/link/update/:id
  redirectClose: axc/datamanagement/link
  flashSave: backend::lang.form.create_success

update:
  title: backend::lang.form.update_title
  redirect: axc/datamanagement/link/update/:id
  redirectClose: axc/datamanagement/link
  flashSave: backend::lang.form.update_success
  flashDelete:  backend::lang.form.delete_success