###
 # @author Alex Carrega <contact@alexcarrega.com>
 # @license http://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
 ##

name: axc.datamanagement::lang.slideshow.label.singular
form: @/plugins/axc/datamanagement/models/slideshow/fields.yaml
modelClass: AxC\DataManagement\Models\Slideshow
defaultRedirect: axc/datamanagement/slideshow

create:
  title: backend::lang.form.create_title
  redirect: axc/datamanagement/slideshow/update/:id
  redirectClose: axc/datamanagement/slideshow
  flashSave: backend::lang.form.create_success

update:
  title: backend::lang.form.update_title
  redirect: axc/datamanagement/slideshow/update/:id
  redirectClose: axc/datamanagement/slideshow
  flashSave: backend::lang.form.update_success
  flashDelete:  backend::lang.form.delete_success